### ISSUE TITLE
Please put AppImage on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [darkr4y/freerdp-pth#1]
Please upload `appimagetool-x86_64.AppImage` to https://github.com/darkr4y/freerdp-pth/releases, thank you.

Reference:
https://robinwinslow.uk/2013/06/11/dont-ever-commit-binary-files-to-git/

**Comment by darkr4y** [comment]
OK , thx for reminding me, have a nice day ;) I ll do it in a moment.

**Comment by darkr4y** [comment]
How about now ?

**Comment by probonopd** [comment]
Thank you very much. Have you thought about contacting the [FreeRDP project](https://github.com/FreeRDP/FreeRDP) so that they could consider making an official AppImage?
